#if !canImport(ObjectiveC)
import XCTest

extension WitnessTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WitnessTests = [
        ("testThatFileChangesAreObserved", testThatFileChangesAreObserved),
        ("testThatFileCreationIsObserved", testThatFileCreationIsObserved),
        ("testThatFileRemovalIsObserved", testThatFileRemovalIsObserved),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(WitnessTests.__allTests__WitnessTests),
    ]
}
#endif
